apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geoserver-instance
spec:
  tls: 
    - hosts:
        - geoserver-satellite-images.lab.sspcloud.fr
  rules:
  - host:  geoserver-satellite-images.lab.sspcloud.fr

    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: geoserver-instance
            port:
              number: 8080
