apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geoserver-pod
spec:
  serviceName: geoserver-service
  replicas: 1
  selector:
    matchLabels:
      app: geoserver-pod
  template:
    metadata:
      labels:
        app: geoserver-pod
    spec:
      containers:
        - name: geoserver
          image: kartoza/geoserver:2.23.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: geoserver-configmap
          env:
            - name: GEOSERVER_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: my-geoserver-creds
                  key: username
            - name: GEOSERVER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-geoserver-creds
                  key: pwd
          ports:
            - containerPort: 8080
              name: http-geoserver
              protocol: TCP

          # startupProbe:            
          #   httpGet:
          #     path: /geoserver
          #     port: http-geoserver
          #     scheme: HTTP
          #   periodSeconds: 5
          #   failureThreshold: 60

          # livenessProbe:
          #   httpGet:
          #     path: /geoserver
          #     port: http-geoserver
          #     scheme: HTTP
          #   periodSeconds: 10
          #   failureThreshold: 3

          # readinessProbe:
          #   httpGet:
          #     path: /geoserver
          #     port: http-geoserver
          #     scheme: HTTP
          #   periodSeconds: 10
          #   failureThreshold: 3

          volumeMounts:
            - name: geoserver-data-dir
              mountPath: "$(GEOSERVER_DATA_DIR)"
            - name: geowebcache-cache-dir
              mountPath: "$(GEOWEBCACHE_CACHE_DIR)"
          resources:
            requests:
              memory: "16Gi"
              cpu: "3000m"
            limits:
              memory: "100Gi"
              cpu: "30000m"
      
      volumes:
        - name: geoserver-data-dir
          persistentVolumeClaim:
            claimName: geoserver-data-dir-pvc
        - name: geowebcache-cache-dir
          persistentVolumeClaim:
            claimName: geowebcache-cache-dir-pvc
