apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geoserver-pod
spec:
  serviceName: geoserver-service
  replicas: 1
  selector:
    matchLabels:
      app: geoserver-pod
  template:
    metadata:
      labels:
        app: geoserver-pod
    spec:
      initContainers:
        - name: download-images-pod         
          image: minio/mc
          imagePullPolicy: Always 
          command:
            - /bin/sh
            - '-c'
            - |
              # Set up the environment variable for MinIO client
              export MC_HOST_s3=https://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}:@${AWS_S3_ENDPOINT}
    
              # Import cluster geometries
              mc cp -r s3/projet-slums-detection/data-clusters \
                      /dossierimage/ilots

              # Import raw images
              mc cp -r s3/projet-slums-detection/data-raw/PLEIADES/GUADELOUPE/2022/  \
                      /dossierimage/PLEIADES/GUADELOUPE/2022
              mc cp -r s3/projet-slums-detection/data-raw/PLEIADES/GUYANE/2023/  \
                      /dossierimage/PLEIADES/GUYANE/2023
              mc cp -r s3/projet-slums-detection/data-raw/PLEIADES/MARTINIQUE/2022/  \
                      /dossierimage/PLEIADES/MARTINIQUE/2022
              mc cp -r s3/projet-slums-detection/data-raw/PLEIADES/MAYOTTE/2023/  \
                      /dossierimage/PLEIADES/MAYOTTE/2023
              mc cp -r s3/projet-slums-detection/data-raw/PLEIADES/REUNION/2023/  \
                      /dossierimage/PLEIADES/REUNION/2023
              mc cp -r s3/projet-slums-detection/data-raw/PLEIADES/SAINT-MARTIN/2024/  \
                      /dossierimage/PLEIADES/SAINT-MARTIN/2024

              # Import predictions
              mc cp s3/projet-slums-detection/data-prediction/PLEIADES/GUADELOUPE/2022/test/15/predictions.gpkg \
                    /dossierimage/PREDICTIONS/PLEIADES/GUADELOUPE/2022/test/15/predictions.gpkg
              mc cp s3/projet-slums-detection/data-prediction/PLEIADES/GUYANE/2023/test/15/predictions.gpkg \
                    /dossierimage/PREDICTIONS/PLEIADES/GUYANE/2023/test/15/predictions.gpkg
              mc cp s3/projet-slums-detection/data-prediction/PLEIADES/MARTINIQUE/2022/test/15/predictions.gpkg \
                    /dossierimage/PREDICTIONS/PLEIADES/MARTINIQUE/2022/test/15/predictions.gpkg
              mc cp s3/projet-slums-detection/data-prediction/PLEIADES/MAYOTTE/2023/test/15/predictions.gpkg \
                    /dossierimage/PREDICTIONS/PLEIADES/MAYOTTE/2023/test/15/predictions.gpkg
              mc cp s3/projet-slums-detection/data-prediction/PLEIADES/REUNION/2023/test/15/predictions.gpkg \
                    /dossierimage/PREDICTIONS/PLEIADES/REUNION/2023/test/15/predictions.gpkg
              mc cp s3/projet-slums-detection/data-prediction/PLEIADES/SAINT-MARTIN/2024/test/15/predictions.gpkg \
                    /dossierimage/PREDICTIONS/PLEIADES/SAINT-MARTIN/2024/test/15/predictions.gpkg
          env:
            - name: AWS_S3_ENDPOINT
              value: minio.lab.sspcloud.fr
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: my-s3-creds
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: my-s3-creds

          volumeMounts:
            - name: geoserver-data-dir
              mountPath: /dossierimage

      containers:
        - name: geoserver
          image: kartoza/geoserver:2.23.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: geoserver-configmap
          env:
            - name: GEOSERVER_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: my-geoserver-creds
                  key: username
            - name: GEOSERVER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-geoserver-creds
                  key: pwd
            - name: AWS_S3_ENDPOINT
              value: minio.lab.sspcloud.fr
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: my-s3-creds
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: my-s3-creds
            - name: MC_HOST_s3
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: mc-s3
          ports:
            - containerPort: 8080
              name: http-geoserver
              protocol: TCP

              startupProbe:            
                httpGet:
                  path: /geoserver
                  port: http-geoserver
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 60
                failureThreshold: 10
    
              livenessProbe:
                httpGet:
                  path: /geoserver
                  port: http-geoserver
                  scheme: HTTP
                periodSeconds: 60
                failureThreshold: 10
    
              readinessProbe:
                httpGet:
                  path: /geoserver
                  port: http-geoserver
                  scheme: HTTP
                periodSeconds: 60
                failureThreshold: 10

          volumeMounts:
            - name: geoserver-data-dir
              mountPath: /opt/geoserver/data_dir
            - name: geowebcache-cache-dir
              mountPath: /opt/geoserver/data_dir/gwc
          resources:
            requests:
              memory: "75Gi"
              cpu: "3000m"
            limits:
              memory: "100Gi"
              cpu: "30000m"
      
      volumes:
        - name: geoserver-data-dir
          persistentVolumeClaim:
            claimName: geoserver-data-dir-pvc
        - name: geowebcache-cache-dir
          persistentVolumeClaim:
            claimName: geowebcache-cache-dir-pvc