geoserver:
  geoserverUser: "admin"

  # For prefilled password
  # It will be stored in secret later
  geoserverPassword: "admin"

  # Define this for extra GeoServer environment variables
  extraPodEnv: |
    - name: GEOSERVER_CSRF_DISABLED
      value: "true"

  # This will be evaluated as pod spec
  extraPodSpec: |
    initContainers:
      - name: download
        image: minio/mc
        command: ["/bin/sh", "-c"]
        args:
        - |
          export MC_HOST_s3=https://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}:@${AWS_S3_ENDPOINT} &&
          echo MC_HOST_s3 &&
          mc cp --recursive s3/projet-slums-detection/data-geoserver/ilots/  /dossierimage/data_dir/ilots
        env:
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        volumeMounts:
        - name: geoserver-data-dir
          mountPath: /dossierimage

  probe: |
    livenessProbe:
      httpGet:
        path: /geoserver
        port: http-geoserver
        scheme: HTTP
      failureThreshold: 3
      successThreshold: 1
      periodSeconds: 10

  persistence:
    geoserverDataDir:
      enabled: true
      existingClaim: false
      mountPath: /opt/geoserver/data_dir
      subPath: "data_dir"
      size: 40Gi
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      annotations: {}
    geowebcacheCacheDir:
      enabled: false
      existingClaim: false
      mountPath: /opt/geoserver/data_dir/gwc
      subPath: "gwc"
      size: 8Gi
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      annotations: {}
  resources:
    requests:
      memory: "16Gi"  # Request at least 2GB of RAM.
      cpu: "3000m"   # Request at least 1000 millicores, equivalent to 1 CPU core.
    limits:
      memory: "100Gi"  # Limit to a maximum of 4GB of RAM.
      cpu: "30000m"   