apiVersion: v1
kind: ConfigMap
metadata:
  name: geoserver-test-configmap
  namespace: projet-slums-detection
data:
  GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
  GEOWEBCACHE_CACHE_DIR: /opt/geoserver/data_dir/gwc
  GEOSERVER_CSRF_DISABLED: "true"
  INSTALL_EXTENSIONS: "true"
  COMMUNITY_EXTENSIONS: cog-plugin
  STABLE_EXTENSIONS: gwc-s3-plugin
  ACTIVATE_ALL_STABLE_EXTENSIONS: "false"
  ACTIVATE_ALL_COMMUNITY_EXTENSIONS: "false"
  CHOWN_DATA_DIR: "true"
  CHOWN_GWC_DATA_DIR: "true"
  MAXIMUM_MEMORY: "75G"
